---
deployment:
  tasks:
    - echo "[DEPLOY] Starting deploy..."
    - export DEPLOYPATH=/home/sepherot/awaisali.ca
    - echo "[DEPLOY] Installing node modules..."
    - npm install # install all npm modules
    - echo "[DEPLOY] Building app..."
    - npm run build # this should build directly into DEPLOYPATH if specified
    - echo "[DEPLOY] Finish deploy."
