---
deployment:
  tasks:
    - echo "[DEPLOY] Starting deploy..."
    - export DEPLOYPATH=/home/sepherot/awaisali.ca
    - echo "[DEPLOY] Initializing NVM..."
    - source ~/.nvm/nvm.sh # initialize nvm
    - echo "[DEPLOY] Installing node modules..."
    - ~/.local/bin/npm install # install all npm modules
    - echo "[DEPLOY] Building app..."
    - ~/.local/bin/npm run build -- --max-old-space-size=1024 # this should build directly into DEPLOYPATH if specified
    - echo "[DEPLOY] Finish deploy."
