---
deployment:
  tasks:
    - echo "start deploy..."
    - export DEPLOYPATH=/home/sepherot/awaisali.ca
    - npm install # install all npm modules
    - npm run build-prod # this should build directly into DEPLOYPATH
    - echo "end deploy."
