---
deployment:
  tasks:
    - echo "start deploy..."
    - DEPLOYPATH=/home/sepherot/awaisali.ca
    - npm install # install all npm modules
    - npm run build # this should build directly into DEPLOYPATH if specified
    - echo "end deploy."
